# Generated by Django 5.1.7 on 2026-02-16 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('fabric', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('base_price', models.FloatField()),
                ('stock_quantity', models.PositiveIntegerField()),
                ('image', models.FileField(upload_to='media')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.category')),
            ],
        ),
    ]
