# Generated by Django 5.1.7 on 2026-03-14 05:58

import siteadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0004_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='products', validators=[siteadmin.models.validate_jpg]),
        ),
    ]
