# Generated by Django 5.1.7 on 2026-03-14 06:03

import siteadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products', validators=[siteadmin.models.validate_jpg]),
        ),
    ]
