# Generated by Django 5.1.7 on 2026-03-28 07:09

import siteadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_alter_product_fabric_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products', validators=[siteadmin.models.validate_jpg]),
        ),
    ]
