# Generated by Django 5.1.7 on 2026-02-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_order_carrier_remove_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
