# Generated by Django 5.1.7 on 2026-02-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_carrier_order_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
