# Generated by Django 5.2.11 on 2026-02-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_order_shipping_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='postalcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reg',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
